name: Debug Win11 ARM64 fuzz build

on: [push]

jobs:
  debug:
    runs-on: windows-11-arm
    steps:
      - name: Checkout roc-lang/roc
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6.0.2
        with:
          repository: roc-lang/roc

      - uses: msys2/setup-msys2@v2
        id: setup-msys2

      - uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29 # 2.2.1
        with:
          version: 0.16.0
          use-cache: true

      - name: Run fuzz build
        run: zig build -Dfuzz -Dsystem-afl=false -Doptimize=ReleaseFast

      - name: Setup tmate session
        if: failure()
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
          msys2-location: ${{ steps.setup-msys2.outputs.msys2-location }}
